server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9813
web:
  upload-path: f:/upload/
spring:
  redis:
    password: ''
    port: 6379
    database: 0
    host: 10.1.0.172
#    host: localhost
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制

